# Generated by Django 6.0.4 on 2026-05-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpStatusCatalog',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description_es', models.TextField()),
                ('category', models.CharField(choices=[('success', 'Éxito'), ('redirect', 'Redirección'), ('client_error', 'Error del cliente'), ('server_error', 'Error del servidor')], max_length=20)),
            ],
            options={
                'verbose_name': 'Código HTTP',
                'ordering': ['code'],
            },
        ),
    ]
